name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install system dependencies
      run: sudo apt-get install -y libasound2-dev libudev-dev
    - name: Cache Build Artifacts
      uses: actions/cache@v4
      with:
        path: targets
        key: cargo-target
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
